language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: NsUbt9sVZi0uLdmu3dXRf5FrZeH+8//4Rpyta8S+Lv+2cPAanTb24e9Ld+NgKiJ6Nl2oR9L2nenTpixqemIlY9lm8W2Lj9lxXnnOxF2+0BghmxALRd5M1n/CqTZqRxFDaknJeGRg7JIBOvtJur9zQejW+PJjvVgTkc8lnFivlt4=
  - secure: Sh5hjaAlL+N2B47ftZaSh4+/UbZyNQss+Uv05XR4Au2j66lWN4nX9y2pBxFMLdXn8IbxBkLD2MfdOL9APM6M4AYvSjpRNYEwviP9QhnMWnbcK9migOlhzNr1/UOJxPQO0n3wOZtWLUsaO/qxtrC3MTPSuhIRWMzGvrn5j3jNoHY=
